### ISSUE TITLE
Get error during baseline running

### ISSUE THREAD

**Issue by cloudygoose** [sarahwie/attention#3]
Hi, thanks for providing the code, but I got the following error:

./run_baselines.sh imdb
Traceback (most recent call last):
  File "train_and_run_experiments_bc.py", line 69, in <module>
    train_dataset_on_encoders(dataset, args, exp_name)
TypeError: train_dataset_on_encoders() takes 2 positional arguments but 3 were given

The call seems to be incompatible to https://github.com/successar/AttentionExplanation/blob/master/ExperimentsBC.py

**Comment by sarahwie** [comment]
It looks like your imports might be broken if you also have a `Transparency` directory from cloning the other repository. In this repo, `train_dataset_on_encoders()` does take 3 arguments.

**Comment by cloudygoose** [comment]
Ah, okay, I misunderstood, I thought the Transparency is meaning the original directory.
By changing Transparency to this repo, I got the following error:
```
attention_is_notnot/Transparency/model/Binary_Classification.py", line 13, in <module>
    from Transparency.model.modules.Decoder import AttnDecoder, FrozenAttnDecoder, PretrainedWeightsDecoder
ImportError: cannot import name 'PretrainedWeightsDecoder' from 'Transparency.model.modules.Decoder' (.../attention_is_notnot/Transparency/model/modules/Decoder.py)
```
I check that PretrainedWeightsDecoder does not exist in your Decoder.py
is something missing?

Thanks!

**Comment by sarahwie** [comment]
This is a bug. It should be `PretrainedWeightsAttnDecoder`.

**Comment by sarahwie** [comment]
I'll also clarify that the repo must be cloned into a folder named `Transparency`.

**Comment by cloudygoose** [comment]
seems to run, thanks!

**Comment by sarahwie** [comment]
Thanks for reporting. I've just pushed a fix for these issues, for anyone else reading this thread. And let me know if you run into anything else.
