### ISSUE TITLE
Is this repo suitable for my task?

### ISSUE THREAD

**Issue by sangyx** [sarahwie/attention#5]
Hi, I'm trying to use this repo to check whether the attention used in my task is useful. However, I'm not sure which experiment I need to do to validate it. In addition, my task is a more complex regression task, not just using a LSTM to do classification. Could I use this repo for my task, or I need to do some modification?

**Comment by yuvalpinter** [comment]
Hi, thanks for using our repo! Yes, I think checking whether attention is useful is a good use case for it. Depending on your architecture, the BOW experiment might be most suitable (3.3), but any of the others might work just as well. Good luck!
